- es/proyecto.md
- fr/projet.md
- project.md
Merci de reviewer les attributions de chacun.
> psc = psc + Louca Lerch

- _posts/2015-07-01-geocom2015-compte-rendu-es.md
> Traducción del articulo de la jornada GEOCOM 2015 al español

- _posts/2015-07-13-georchestra-15.06-es.md
- es/comunidad.md
@fvanderbiest Thanks for assigning me these issues, this way I know what's new in geOrchestra, every six months :)
> Fixes #54 and #55

- documentation.md
- es/documentacion.md
- es/software.md
- fr/documentation.md
- fr/logiciel.md
- software.md
To be merged when the release is done.
> preparing the 15.12 release

- _posts/2016-05-16-geocom-2016-en.md
- _posts/2016-05-16-geocom-2016-es.md
- _posts/2016-05-16-geocom-2016-fr.md
Merci au PSC de relire, corriger, traduire (en / es) avant publication (idéalement mardi).
> geocom 2016 post

- community.md
- es/comunidad.md
- es/software.md
- fr/logiciel.md
- software.md
Related to https://github.com/georchestra/georchestra.github.io/issues/71#issuecomment-439214125
> Fix some broken URL

- es/proyecto.md
- fr/projet.md
- project.md
To keep track of the changes. To be completed
> Update PSC members list

- _posts/2021-05-31-geocom-2021-en.md
- _posts/2021-05-31-geocom-2021-es.md
- _posts/2021-05-31-geocom-2021-fr.md
We should tell which session is in what language, and when they can get translated content
> Add language information

- .travis.yml
- README.md
link to georchestra/georchestra.github.io/issues/#105
Create branch to test with travis
> update rubby version and add missing dependencies

- css/georchestra-theme.css
> #111 Fix scrollbar

- _includes/home/en_home.html
- _includes/home/es_home.html
- _includes/home/fr_home.html
This PR fix display title GEOCOM
> #113 fix display title GEOCOM

- es/software.md
- fr/logiciel.md
- software.md
close #78
(cherry picked from commit 2d62070d505e9b7e7608aa5fa2daf2734b89ce25)
> update softwares versions and release table

- fr/projet.md
ajout de Catherine au PSC et des geocom 2019/2021
> update members list and geocom's edition

- software.md
> update version releases matrix

- .github/workflows/build_and_test_website.yml
Attribute name changed : https://github.com/gjtorikian/html-proofer
file_ignore to ignore_files
> Update html check attribute

- community.md
- documentation.md
- es/comunidad.md
- es/documentacion.md
- fr/communaute.md
- fr/documentation.md
- Delete instance of geotiticaca 
- Delete link telekom
- Update version geoserver and geonetwork
> Fix url website 

- _includes/home/en_home.html
- _includes/home/es_home.html
- _includes/home/fr_home.html
Added date, place and link to the page with program and registration
> Update home page with geocom 2023 information

- public/geocom2023/geocom-2023.html
> Geocom 2023 - Ajout de la vidéo de Séverin MENARD (Les libres géographes)

- community.md
- es/comunidad.md
- fr/communaute.md
GeoNode won https://geo.gob.bo/catalogue
> GeoBolivia is not using geOrchestra anymore :(

- _includes/card_presentation.html
- css/georchestra-theme.css
- public/geocom2024/index.html
@MaelREBOUX  you now need to add the parameter `video_url=""` for each presentation
> Update presentation structure card with icons for geocom2024
